export const JUZ_DATA: Record<number, { subtitle: string, count: number }> = {
  1: { subtitle: "(2 Surahs) Al-Fatiha, Al-Baqarah", count: 2 },
  2: { subtitle: "(1 Surah) Al-Baqarah", count: 1 },
  3: { subtitle: "(2 Surahs) Al-Baqarah, Aal-E-Imran", count: 2 },
  4: { subtitle: "(2 Surahs) Aal-E-Imran, An-Nisa", count: 2 },
  5: { subtitle: "(1 Surah) An-Nisa", count: 1 },
  6: { subtitle: "(2 Surahs) An-Nisa, Al-Ma'idah", count: 2 },
  7: { subtitle: "(2 Surahs) Al-Ma'idah, Al-An'am", count: 2 },
  8: { subtitle: "(2 Surahs) Al-An'am, Al-A'raf", count: 2 },
  9: { subtitle: "(2 Surahs) Al-A'raf, Al-Anfal", count: 2 },
  10: { subtitle: "(2 Surahs) Al-Anfal, At-Tawbah", count: 2 },
  11: { subtitle: "(3 Surahs) At-Tawbah, Yunus, Hud", count: 3 },
  12: { subtitle: "(2 Surahs) Hud, Yusuf", count: 2 },
  13: { subtitle: "(3 Surahs) Yusuf, Ar-Ra'd, Ibrahim", count: 3 },
  14: { subtitle: "(2 Surahs) Al-Hijr, An-Nahl", count: 2 },
  15: { subtitle: "(2 Surahs) Al-Isra, Al-Kahf", count: 2 },
  16: { subtitle: "(3 Surahs) Al-Kahf, Maryam, Ta-Ha", count: 3 },
  17: { subtitle: "(2 Surahs) Al-Anbiya, Al-Hajj", count: 2 },
  18: { subtitle: "(3 Surahs) Al-Mu'minun, An-Nur, Al-Furqan", count: 3 },
  19: { subtitle: "(3 Surahs) Al-Furqan, Ash-Shu'ara, An-Naml", count: 3 },
  20: { subtitle: "(3 Surahs) An-Naml, Al-Qasas, Al-Ankabut", count: 3 },
  21: { subtitle: "(5 Surahs) Al-Ankabut, Ar-Rum, Luqman, As-Sajdah, Al-Ahzab", count: 5 },
  22: { subtitle: "(4 Surahs) Al-Ahzab, Saba, Fatir, Ya-Sin", count: 4 },
  23: { subtitle: "(4 Surahs) Ya-Sin, As-Saffat, Sad, Az-Zumar", count: 4 },
  24: { subtitle: "(3 Surahs) Az-Zumar, Ghafir, Fussilat", count: 3 },
  25: { subtitle: "(5 Surahs) Fussilat, Ash-Shura, Az-Zukhruf, Ad-Dukhan, Al-Jathiyah", count: 5 },
  26: { subtitle: "(6 Surahs) Al-Ahqaf, Muhammad, Al-Fath, Al-Hujurat, Qaf, Adh-Dhariyat", count: 6 },
  27: { subtitle: "(7 Surahs) Adh-Dhariyat, At-Tur, An-Najm, Al-Qamar, Ar-Rahman, Al-Waqi'ah, Al-Hadid", count: 7 },
  28: { subtitle: "(9 Surahs) Al-Mujadilah, Al-Hashr, Al-Mumtahanah, As-Saff, Al-Jumu'ah, Al-Munafiqun, At-Taghabun, At-Talaq, At-Tahrim", count: 9 },
  29: { subtitle: "(11 Surahs) Al-Mulk, Al-Qalam, Al-Haqqah, Al-Ma'arij, Nuh, Al-Jinn, Al-Muzzammil, Al-Muddaththir, Al-Qiyamah, Al-Insan, Al-Mursalat", count: 11 },
  30: { subtitle: "(37 Surahs) An-Naba, An-Nazi'at, 'Abasa, At-Takwir, Al-Infitar, Al-Mutaffifin, Al-Inshiqaq, Al-Buruj, At-Tariq, Al-A'la, Al-Ghashiyah, Al-Fajr, Al-Balad, Ash-Shams, Al-Layl, Ad-Duha, Ash-Sharh, At-Tin, Al-'Alaq, Al-Qadr, Al-Bayyinah, Az-Zalzalah, Al-'Adiyat, Al-Qari'ah, At-Takathur, Al-'Asr, Al-Humazah, Al-Fil, Quraysh, Al-Ma'un, Al-Kawthar, Al-Kafirun, An-Nasr, Al-Masad, Al-Ikhlas, Al-Falaq, An-Nas", count: 37 }
};
